### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by 4kangjc** [Tencent/flare#110]
噢噢是这样的我看到代码有些地方的格式不太对
@0x804d8000 你们用的clang-format版本是多少
关于google style 头文件的问题, clang-format文件能不能修改做到格式化

**Comment by 0x804d8000** [comment]
应该比较新的版本都可以，我一般不会专门找某个特定版本。

配置文件指定到flare下面的.clang-format应该就可以，现在是有什么地方格式化的不合预期吗

**Comment by 4kangjc** [comment]
> 应该比较新的版本都可以，我一般不会专门找某个特定版本。
> 
> 配置文件指定到flare下面的.clang-format应该就可以，现在是有什么地方格式化的不合预期吗

clang-format 14和clang-format 15格式化出来的有一点点区别, 我想加一个clang-format check的CI

https://github.com/Tencent/flare/blob/d6534086041ae6e31504870db8db88fc391c7e66/flare/fiber/this_fiber_test.cc#L15-L28

这个头文件的顺序应该不对吧, flare下面的.clang-format头文件好像格式化不了这种形式https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
这个得我们自己加blank line

**Comment by 4kangjc** [comment]
![image](https://github.com/Tencent/flare/assets/73515066/68a6cd26-e29f-4d66-b7c9-2c95756d94b7)
这种

**Comment by 0x804d8000** [comment]
这个确实是代码需要修改，应该按照空行分组。分组了之后clang-format应该就没问题了

**Comment by 4kangjc** [comment]
挺多需要format的, 我用clang-format 15格式化了一下整个项目, proto文件感觉没有必要格式化

**Comment by 4kangjc** [comment]
> 这个确实是代码需要修改，应该按照空行分组。分组了之后clang-format应该就没问题了

有没有不需要手动分组的方法:) clang-format承当这个工作

**Comment by 4kangjc** [comment]
> > 这个确实是代码需要修改，应该按照空行分组。分组了之后clang-format应该就没问题了
> 
> 有没有不需要手动分组的方法:) clang-format承当这个工作

我尝试过这个, 但对于`_benchmark.cc`的文件没办法, 而且flare里还有一些`.cc`和`_test.cc`文件里相关的文件不是他本身的前缀, 也不生效
``` yaml
IncludeBlocks:   Regroup
IncludeCategories:
  - Regex:           '^<.*\.h>'
    Priority:        1
  - Regex:           '^<.*'
    Priority:        2
  - Regex:           '^"(google|gperftools|jemalloc|lz4|snappy|nghttp2|zlib|benchmark|jsoncpp|ctemplate|curl|gflags|fmt|gtest|gmock|glog|yaml-cpp|openssl|opentracing|opentracing-cpp|zstd|rapidxml|xxhash|blake3)/'
    Priority:        3
  - Regex:           '.*'
    Priority:        4
```

**Comment by 0x804d8000** [comment]
> > 这个确实是代码需要修改，应该按照空行分组。分组了之后clang-format应该就没问题了
> 
> 有没有不需要手动分组的方法:) clang-format承当这个工作

不分组的话我理解格式化完了应该跟现在这个写法一样，这个也ok啊。也就是有空行的文件就分组格式化，没空行的先一起排序，也不影响什么，后面修改到了对应的文件在相应的处理这样

**Comment by 4kangjc** [comment]
> > > 这个确实是代码需要修改，应该按照空行分组。分组了之后clang-format应该就没问题了
> > 
> > 
> > 有没有不需要手动分组的方法:) clang-format承当这个工作
> 
> 不分组的话我理解格式化完了应该跟现在这个写法一样，这个也ok啊。也就是有空行的文件就分组格式化，没空行的先一起排序，也不影响什么，后面修改到了对应的文件在相应的处理这样

https://github.com/Tencent/flare/blob/d6534086041ae6e31504870db8db88fc391c7e66/flare/rpc/internal/stream_test.cc#L15-L26

git-clang应该检测不到这种情况, 我的意思是git-clang能不能自动格式化成下面这种情况, 而不需要我们自己去分组

```cpp
#include <utility>
#include <vector>

#include "gmock/gmock.h"
#include "gtest/gtest.h"

#include "flare/base/chrono.h"
#include "flare/fiber/latch.h"
#include "flare/fiber/timer.h"
#include "flare/testing/main.h"
```

**Comment by 0x804d8000** [comment]
这个好像我也没听说有什么办法，一直都是手动处理的

**Comment by 4kangjc** [comment]
> 这个好像我也没听说有什么办法，一直都是手动处理的

OK

**Comment by 4kangjc** [comment]
> 这个好像我也没听说有什么办法，一直都是手动处理的

``` yaml
IncludeIsMainRegex: "(_test|_benchmark)?$"
IncludeBlocks:   Regroup
IncludeCategories:
  - Regex:           '^<.*\.h>'
    Priority:        1
  - Regex:           '^<.*'
    Priority:        2
  - Regex:           '^"(google|gperftools|jemalloc|lz4|snappy|nghttp2|zlib|benchmark|jsoncpp|ctemplate|curl|gflags|fmt|gtest|gmock|glog|yaml-cpp|openssl|opentracing|opentracing-cpp|zstd|rapidxml|xxhash|blake3)/'
    Priority:        3
  - Regex:           '.*'
    Priority:        4
```

这个能处理flare中绝大多少的了, 极少部分比如上条PR里你提到了`flare/base/object_pool/thread_local_test.cc`这种才处理不了, 只能这样处理了, 你看可以吗
``` cpp
// clang-format off
#include "flare/base/object_pool.h"
// clang-format on
```
